### ISSUE TITLE
Suggested Addons to DaVinci Output

### ISSUE THREAD

**Issue by martin1968b16** [AndrewSazonov/Davinci#3]
**Suggest to add standard output formats suitable for ShelX and JANA2006:**

ShelX97: %4d%4d%4d%8.2f%8.2f%4d (H K L I_int sigma flag(=1 by default)
ShelX97 with direction cosini:
              %4d%4d%4d%8.2f%8.2f%4d%8.5f%8.5f%8.5f%8.5f%8.5f%8.5f (same as ShelX97 + 6 direction cosini)
D9/ILL: "%6d%4d%4d%4d%10.2f%10.2f%8.2f%8.2f%8.2f%8.2f T=%7.2f PSI=%7.2f FWHM=%7.4f ", \
                      i(=running no.) H K L iobs sigma Theta Omega Chi Phi temperature[psi  fwhm, added for internal use]

**Concerning direction cosini, this is the old routine:**
void directioncosini(double dcos[7],
                     double ttheta,
                     double omega,
                     double chi,
                     double phi,
                     double emat[4][4],
                     int reflextype) {
  /* **************************************** */
  /* Calculate direction cosines (for hklf 4) */
  /* **************************************** */
  int i, j;
  double stth, ctth, somg, comg, schi, cchi, sphi, cphi;
  double x, y, z, o, p, q;

  stth=sin(ttheta);
  ctth=cos(ttheta);
  somg=sin(omega);
  comg=cos(omega);
  schi=sin(chi);
  cchi=cos(chi);
  sphi=sin(phi);
  cphi=cos(phi);

  ctth=-ctth;
  if (reflextype==1) { // reflextype 1 means measured at negative 2theta and omega
    stth=-stth;
    somg=-somg;
  }
  x=        comg*cchi;
  o= x*cphi-somg*sphi;
  p=-x*sphi-somg*cphi;
  q=        comg*schi;
  z=        somg*cchi;
  x= z*cphi+comg*sphi;
  y=-z*sphi+comg*cphi;
  z=        somg*schi;
  j=1;
  for (i=1; i<=3; ++i) {
    dcos[j ]= x*emat[1][i]+y*emat[2][i]+z*emat[3][i];
    dcos[j+1]=stth*(o*emat[1][i]+p*emat[2][i]+q*emat[3][i])+ctth*dcos[j];
    j+=2;
  }
  return;

**Definition of emat (Normalized orienting matrix):**
 for (i=1; i<=3; ++i) {
      x=1.0/sqrt(pow(omat[1][i], 2)+pow(omat[2][i], 2)+pow(omat[3][i],2));
      for (j=1; j<=3; ++j) emat[j][i]=omat[j][i]*x;
    }

**Comment by AndrewSazonov** [comment]
Added in release [v1.0.5](https://github.com/AndrewSazonov/Davinci/tree/v1.0.5)
