### ISSUE TITLE
unable to open more than 350 scans

### ISSUE THREAD

**Issue by vladhutanu** [AndrewSazonov/Davinci#4]
By trying to open more than 350 scans error reprted that, scans of different type are used.
indeed only sth scans are measured. by 350 scans or less Ok, by 351 or any larger do not work anymore.
Please fix in the way than no limit for the scan number occur, let say 10 000.    

This issue is occuring on both windows version 1.0.4 and linux version 1.0.2.

best
Vlad

**Comment by vladhutanu** [comment]
Examples are in experiment p14440 (2018) /current. 
starting from scan 157432 only up to scan 157781 can be opened

**Comment by AndrewSazonov** [comment]
There are no limits on the number of scans. It seems that one of the files (157782) was corrupted. Please, create a new issue and attach the corrupted file in order to check the program.
